MODEL:
    name: "BMN"
    tscale: 100
    dscale: 100
    feat_dim: 400
    prop_boundary_ratio: 0.5
    num_sample: 32
    num_sample_perbin: 3
    anno_file: "data/dataset/bmn/activitynet_1.3_annotations.json"
    feat_path: 'data/dataset/bmn/fix_feat_100'

TRAIN:
    subset: "train"
    epoch: 9
    batch_size: 16
    num_threads: 8
    use_gpu: True
    num_gpus: 4
    learning_rate: 0.001
    learning_rate_decay: 0.1
    lr_decay_iter: 4200
    l2_weight_decay: 1e-4

VALID:
    subset: "validation"
    batch_size: 16
    num_threads: 8
    use_gpu: True
    num_gpus: 4

TEST:
    subset: "validation"
    batch_size: 1
    num_threads: 1
    snms_alpha: 0.001
    snms_t1: 0.5
    snms_t2: 0.9
    output_path: "data/output/EVAL/BMN_results"
    result_path: "data/evaluate_results"

INFER:
    subset: "test"
    batch_size: 1
    num_threads: 1
    snms_alpha: 0.4
    snms_t1: 0.5
    snms_t2: 0.9
    filelist: 'data/dataset/bmn/infer.list'
    output_path: "data/output/INFER/BMN_results"
    result_path: "data/predict_results"
