version: 1.0
distillers:
    fsp_distiller:
        class: 'FSPDistiller'
        teacher_pairs: [['res2a_branch2a.conv2d.output.1.tmp_0', 'res3a_branch2a.conv2d.output.1.tmp_0']]
        student_pairs: [['depthwise_conv2d_1.tmp_0', 'conv2d_3.tmp_0']]
        distillation_loss_weight: 1
    l2_distiller:
        class: 'L2Distiller'
        teacher_feature_map: 'res_fc.tmp_0'
        student_feature_map: 'fc_0.tmp_0'
        distillation_loss_weight: 1
strategies:
    distillation_strategy:
        class: 'DistillationStrategy'
        distillers: ['fsp_distiller', 'l2_distiller']
        start_epoch: 0
        end_epoch: 130
compressor:
    epoch: 130
    checkpoint_path: './checkpoints/'
    strategies:
        - distillation_strategy
