version: 1.0
distillers:
    l2_distiller:
        class: 'L2Distiller'
        teacher_feature_map: 'res_fc.tmp_0'
        student_feature_map: 'fc_0.tmp_0'
        distillation_loss_weight: 1
strategies:
    distillation_strategy:
        class: 'DistillationStrategy'
        distillers: ['l2_distiller']
        start_epoch: 0
        end_epoch: 130
compressor:
    epoch: 130
    checkpoint_path: './checkpoints/'
    strategies:
        - distillation_strategy
