DATAAUG:
    RAND_SCALE_MIN: 0.5
    RAND_SCALE_MAX: 2.0
    BASE_SIZE: 1024
    CROP_SIZE: 769
    EXTRA: True
TRAIN_BATCH_SIZE_PER_GPU: 2
NUM_TRAINERS: 4
EVAL_BATCH_SIZE: 1
DATASET:
    DATASET_NAME: "cityscapes"
    DATA_DIR: "./data/cityscapes/"
    IMAGE_TYPE: "rgb"  # choice rgb or rgba
    NUM_CLASSES: 19
    TEST_FILE_LIST: "./data/cityscapes/cityscapes_list/test.lst"
    TRAIN_FILE_LIST: "./data/cityscapes/cityscapes_list/train.lst"
    VAL_FILE_LIST: "./data/cityscapes/cityscapes_list/val.lst"
    IGNORE_INDEX: 255
    DATA_DIM: 3
MODEL:
    MODEL_NAME: "pspnet"
    DEFAULT_NORM_TYPE: "bn"
    MULTI_LOSS_WEIGHT: [1.0, 0.4]
    BACKBONE: "resnet"
    BACKBONE_LAYERS: 101
    BACKBONE_MULTI_GRID: True
    PSPNET:
        DEPTH_MULTIPLIER: 1
        AuxHead: True
TRAIN:
    MODEL_SAVE_DIR: "snapshots/pspnet_res101_cityscapes/"
    PRETRAINED_MODEL_DIR: "./pretrained_model/resnet101_v2/"
    SNAPSHOT_EPOCH: 1
TEST:
    TEST_MODEL: "snapshots/pspnet_res101_cityscapes"
    BASE_SIZE: 2048
    CROP_SIZE: 769
    SLIDE_WINDOW: True
SOLVER:
    LR: 0.01
    LR_POLICY: "poly"
    OPTIMIZER: "sgd"
    NUM_EPOCHS: 80
    LOSS: "['softmax_loss']"

